services:
  - type: web
    name: school-api
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate && python manage.py reset_admin_password
    startCommand: gunicorn school_api.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: DJANGO_SETTINGS_MODULE
        value: school_api.settings
      - key: ADMIN_PASSWORD
        value: AdminP@ssw0rd2024!
